# Script generated by ChatGPT to run mqtt

import paho.mqtt.client as mqtt

# HiveMQ Cloud Credentials
MQTT_BROKER = "8c64562f19ed429cb2d15aadab7c35bc.s1.eu.hivemq.cloud"
MQTT_PORT = 8883  # TLS Port
MQTT_USER = "hivemq.webclient.1742259605532"  # Replace with your new username
MQTT_PASS = "HeZX#5k$90P:;zWQ3pgf"  # Replace with your new password
MQTT_TOPIC = "nexys/data"

# Callback when connected
def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print("Connected to HiveMQ Cloud!")
        client.subscribe(MQTT_TOPIC)
    else:
        print(f"Connection failed with code {rc}")

# Callback when a message is received
def on_message(client, userdata, msg):
    print(f"Received message: {msg.topic} -> {msg.payload.decode()}")

# Create MQTT Client with TLS
client = mqtt.Client()
client.tls_set()  # Enables secure TLS encryption
client.username_pw_set(MQTT_USER, MQTT_PASS)

# Set callbacks
client.on_connect = on_connect
client.on_message = on_message

# Connect to the HiveMQ Cloud broker
client.connect(MQTT_BROKER, MQTT_PORT, 60)

# Start MQTT loop
client.loop_forever()
