# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SimpleLock/DigitalLockv2/DigitalLockv2.srcs/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1.xci
# IP: The module: 'dlembsys_axi_uartlite_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/SimpleLock/DigitalLockv2/DigitalLockv2.srcs/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1.xci
# IP: The module: 'dlembsys_axi_uartlite_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_axi_uartlite_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
