# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/nexysA7fpga.xdc

# Block Designs: bd/embsys9/embsys9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9 || ORIG_REF_NAME==embsys9} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_microblaze_0_0/embsys9_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_microblaze_0_0 || ORIG_REF_NAME==embsys9_microblaze_0_0} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_axi_gpio_0_0/embsys9_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_axi_gpio_0_0 || ORIG_REF_NAME==embsys9_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_axi_uartlite_0_0 || ORIG_REF_NAME==embsys9_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_dlmb_v10_1/embsys9_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_dlmb_v10_1 || ORIG_REF_NAME==embsys9_dlmb_v10_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_ilmb_v10_1/embsys9_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_ilmb_v10_1 || ORIG_REF_NAME==embsys9_ilmb_v10_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_dlmb_bram_if_cntlr_1/embsys9_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys9_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_ilmb_bram_if_cntlr_1/embsys9_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys9_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_lmb_bram_1/embsys9_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_lmb_bram_1 || ORIG_REF_NAME==embsys9_lmb_bram_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_xbar_1/embsys9_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_xbar_1 || ORIG_REF_NAME==embsys9_xbar_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_microblaze_0_axi_periph_1/embsys9_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_microblaze_0_axi_periph_1 || ORIG_REF_NAME==embsys9_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_mdm_1_1/embsys9_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_mdm_1_1 || ORIG_REF_NAME==embsys9_mdm_1_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_clk_wiz_1_1/embsys9_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_clk_wiz_1_1 || ORIG_REF_NAME==embsys9_clk_wiz_1_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_rst_clk_wiz_1_100M_1/embsys9_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==embsys9_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/embsys9/ip/embsys9_reset_inv_0_1/embsys9_reset_inv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys9_reset_inv_0_1 || ORIG_REF_NAME==embsys9_reset_inv_0_1} -quiet] -quiet

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/embsys9_ooc.xdc
