# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SimpleLock/Vivado9/Vivado9.srcs/sources_1/bd/embsys9/ip/embsys9_lmb_bram_1/embsys9_lmb_bram_1.xci
# IP: The module: 'embsys9_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_lmb_bram_1/embsys9_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/SimpleLock/Vivado9/Vivado9.srcs/sources_1/bd/embsys9/ip/embsys9_lmb_bram_1/embsys9_lmb_bram_1.xci
# IP: The module: 'embsys9_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_lmb_bram_1/embsys9_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
