# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SimpleLock/Vivado9/Vivado9.srcs/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0.xci
# IP: The module: 'embsys9_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/SimpleLock/Vivado9/Vivado9.srcs/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0.xci
# IP: The module: 'embsys9_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/SimpleLock/Vivado9/Vivado9.gen/sources_1/bd/embsys9/ip/embsys9_axi_uartlite_0_0/embsys9_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys9_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
