# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/nexysA7fpga.xdc

# Block Designs: bd/dlembsys/dlembsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys || ORIG_REF_NAME==dlembsys} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_microblaze_0_0/dlembsys_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_microblaze_0_0 || ORIG_REF_NAME==dlembsys_microblaze_0_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_dlmb_v10_0/dlembsys_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_dlmb_v10_0 || ORIG_REF_NAME==dlembsys_dlmb_v10_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_ilmb_v10_0/dlembsys_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_ilmb_v10_0 || ORIG_REF_NAME==dlembsys_ilmb_v10_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_dlmb_bram_if_cntlr_0/dlembsys_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==dlembsys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_ilmb_bram_if_cntlr_0/dlembsys_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==dlembsys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_lmb_bram_0/dlembsys_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_lmb_bram_0 || ORIG_REF_NAME==dlembsys_lmb_bram_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_xbar_0/dlembsys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_xbar_0 || ORIG_REF_NAME==dlembsys_xbar_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_microblaze_0_axi_periph_0/dlembsys_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==dlembsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_mdm_1_0/dlembsys_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_mdm_1_0 || ORIG_REF_NAME==dlembsys_mdm_1_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_clk_wiz_1_0/dlembsys_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_clk_wiz_1_0 || ORIG_REF_NAME==dlembsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_rst_clk_wiz_1_100M_0/dlembsys_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==dlembsys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_axi_uartlite_0_1/dlembsys_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_axi_uartlite_0_1 || ORIG_REF_NAME==dlembsys_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_axi_bram_ctrl_0_0/dlembsys_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==dlembsys_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_axi_bram_ctrl_0_bram_0/dlembsys_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==dlembsys_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_reset_inv_0_0/dlembsys_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_reset_inv_0_0 || ORIG_REF_NAME==dlembsys_reset_inv_0_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_auto_pc_2/dlembsys_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_auto_pc_2 || ORIG_REF_NAME==dlembsys_auto_pc_2} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_auto_pc_0/dlembsys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_auto_pc_0 || ORIG_REF_NAME==dlembsys_auto_pc_0} -quiet] -quiet

# IP: bd/dlembsys/ip/dlembsys_auto_pc_1/dlembsys_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dlembsys_auto_pc_1 || ORIG_REF_NAME==dlembsys_auto_pc_1} -quiet] -quiet

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/dlembsys_ooc.xdc
