# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SimpleLock/DigitalLockv2/DigitalLockv2.srcs/sources_1/bd/dlembsys/ip/dlembsys_ilmb_v10_0/dlembsys_ilmb_v10_0.xci
# IP: The module: 'dlembsys_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_ilmb_v10_0/dlembsys_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/SimpleLock/DigitalLockv2/DigitalLockv2.srcs/sources_1/bd/dlembsys/ip/dlembsys_ilmb_v10_0/dlembsys_ilmb_v10_0.xci
# IP: The module: 'dlembsys_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SimpleLock/DigitalLockv2/DigitalLockv2.gen/sources_1/bd/dlembsys/ip/dlembsys_ilmb_v10_0/dlembsys_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dlembsys_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
